spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moi_caq_db
    username: root
    password: include73
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        trueetch_size: 100
logging.level:
  org.hibernate.SQL: debug